### ISSUE TITLE
Uploading 10,000 assetsForSale in buyer-mints-nft branch

### ISSUE THREAD

**Issue by iskanderandrews** [austintgriffith/scaffold-eth#184]
Hi, 

So I forked this branch for working on an NFT project using this contract. 
https://github.com/austintgriffith/scaffold-eth/blob/buyer-mints-nft/packages/hardhat/contracts/YourCollectible.sol

And I was using the feature of allowing the buyer to mint the token, so I was trying to deploy the contract with the `assetsForSale[]`
https://github.com/austintgriffith/scaffold-eth/blob/b810f9054a22517b305494e405d1de7a1ea3bc2e/packages/hardhat/contracts/YourCollectible.sol#L17

But with 10,000 IPFS Hash, so the result was a crazy amount of gas has been used as more than 222,000,000 

So this contract template not optimized for a big (n) of items. 

My question here, 
**What would be the best-optimized way for adding those hashes (10000) into the contract?**

The main issue here is we want a way to allow the contract to verify the hash to be minted but without having these crazy gas units used. 

Thanks so much! 

cc: (@blockboard-co)

**Comment by azf20** [comment]
Hey! Try out the merkle root branch by @viraj124 @ironsoul0 and @sadda11asm which supports exactly that use case https://github.com/austintgriffith/scaffold-eth/tree/merkle-root-buyer-mints

**Comment by viraj124** [comment]
yeah @iskanderandrews if you follow the readme so basically instead of storing the iphs hashes on chain you can just store the Merkel root and do minting by that's what this branch does so you can edit this [file](https://github.com/austintgriffith/scaffold-eth/blob/merkle-root-buyer-mints/packages/react-app/scripts/example.json) and add the hashes o the artwork you wanna mint on-chain so this branches saves gas in terms of not storing the hashes on chain
