### ISSUE TITLE
useContractReader not working properly when calling it in a view other than app.js

### ISSUE THREAD

**Issue by pabloruiz55** [austintgriffith/scaffold-eth#185]
How to reproduce:

1- Start a new project from master branch
2- In ExampleUI.js add the following lines:

```
  const readContracts2 = useContractLoader(localProvider);
  const purpose2 = useContractReader(readContracts2, "YourContract", "purpose");
  console.log(purpose2);
```

Also have it render <h4>purpose: {purpose2}</h4>

--

3- If you navigate to ExampleUI you will see `purpose2` properly rendered/logged
4- BUT, if you navigate to another section (without reloading/refreshing the browser) and then back to ExampleUI, `purpose2` is undefined. 
5- If you refresh the browser `purpose2` is right, but if you move between other routes/view, it's not.

Note: If you add a pollTime parameter to `useContractReader` the issue is fixed, but it's not ideal.

**Comment by azf20** [comment]
Hello. I think this might be a quirk of local development, because it is waiting for a new block to update the values, and there aren't any on the local chain when you navigate to the new page, unless you do something. This doesn't happen when you navigate straight to the page, because ethers sends an initial new block event on initiation (which is in the past for the provider if you navigate to ExampleUI)
There is a quite easy fix which I don't love which keeps track of whether it has been executed at all, and executes it if not, but more elegant solutions are welcome

**Comment by pabloruiz55** [comment]
Oh I see! Tbh I didn't check if I could reproduce it outside a local environment. I'll check it out and check your proposed fix.
