### ISSUE TITLE
Scaffold-eth React-app should gracefully handle not having an internet connection

### ISSUE THREAD

**Issue by pabloruiz55** [austintgriffith/scaffold-eth#198]
We should be able to develop in airplane mode / Chrome offline simulation while connected to a local chain.
Instead, we get the following error upon page load. 

<img width="1414" alt="Screen Shot 2021-06-14 at 1 11 12 PM" src="https://user-images.githubusercontent.com/526558/121924438-470be780-cd12-11eb-9088-7f76aa920d3e.png">

First step should be to handle the error so the app still manages to load.

Second step should be reviewing all the components the basic template has so we remove the internet connectivity dependency. I.E: When connecting to local chain the default template still tries to connect to mainnet rpc node.

**Comment by TaldenV** [comment]
I'm on a road trip and would love to see this feature implemented. Because I'm going to be offline anyway, I'll be able to spend some time looking into handling the errors so the app can still load. I created and pulled a branch, but decided I should probably be commenting on the issue before trying to do a pull request.

**Comment by pabloruiz55** [comment]
> I'm on a road trip and would love to see this feature implemented. Because I'm going to be offline anyway, I'll be able to spend some time looking into handling the errors so the app can still load. I created and pulled a branch, but decided I should probably be commenting on the issue before trying to do a pull request.

Awesome! Let me know when you have something and I'll test it out.

**Comment by TaldenV** [comment]
Ok, I was able to find some fixes. It looks like the main things that are causing the connection issues to pop up are the gas hook, the faucet, and the mainnet connection in app.jsx. I was able to comment out all of the connection issues. It might be due to getting rid of the debug warnings, but once you get rid of the warnings you can access and edit the dapp just fine. Once in airplane mode, you just need to add the hardhat RPC network to the wallet, then add a hardhat account pre-loaded with 100 eth. The RPC network and accounts can be found in the terminal immediately after running the yarn chain.

One issue I found is that the hardhat accounts don’t reset in the metamask wallet once the chain is closed and reopened. It seems to be an issue that the hardhat community is aware of/working on (Reference: https://github.com/MetaMask/metamask-extension/issues/10290).

Perhaps it would be cool to have airplane mode be a new feature for eth-build. I kinda like how the theme switcher button looks, so I messed around with some of the code from the ThemeSwitcher component and pasted it into a new AirplaneMode component. I was thinking that I would be able to just pass in a variable — like you would pass a pointer to a function in C++ — to the AirplaneMode component that would flip a true/false statement in the App.jsx which would activate/deactivate all of the connections and maybe pop up a screen with instructions to connecting a wallet. As you all might already know, there are a couple of problems with this approach; (1) I’m still new to web development — specifically, React — so I found out that React components don’t edit variables that are passed in. (2) Having a variable with a bunch of if statements would clutter up the otherwise clean code in app.jsx.

I think this could be a cool feature, so while I look into understanding React better, I would love some guidance/hints on what to look into next

**Comment by pabloruiz55** [comment]
@TaldenV thanks for taking a look at this.
Please check my PR to see if this is what you had in mind. 
Would be great if you could checkout that branch and see if it works fine for you.
https://github.com/austintgriffith/scaffold-eth/pull/210

**Comment by pabloruiz55** [comment]
Closed by #199
